<?php
/**
 * InlineResponse200Hydrasearch
 *
 * PHP version 5
 *
 * @category Class
 * @package  VentureLeap\UserService
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * User API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.22-SNAPSHOT
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace VentureLeap\UserService\Model;

use \ArrayAccess;
use \VentureLeap\UserService\ObjectSerializer;

/**
 * InlineResponse200Hydrasearch Class Doc Comment
 *
 * @category Class
 * @package  VentureLeap\UserService
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class InlineResponse200Hydrasearch implements ModelInterface, ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $swaggerModelName = 'inline_response_200_hydrasearch';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerTypes = [
        'type' => 'string',
'hydratemplate' => 'string',
'hydravariable_representation' => 'string',
'hydramapping' => '\VentureLeap\UserService\Model\InlineResponse200HydrasearchHydramapping[]'    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerFormats = [
        'type' => null,
'hydratemplate' => null,
'hydravariable_representation' => null,
'hydramapping' => null    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerFormats()
    {
        return self::$swaggerFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'type' => '@type',
'hydratemplate' => 'hydra:template',
'hydravariable_representation' => 'hydra:variableRepresentation',
'hydramapping' => 'hydra:mapping'    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'type' => 'setType',
'hydratemplate' => 'setHydratemplate',
'hydravariable_representation' => 'setHydravariableRepresentation',
'hydramapping' => 'setHydramapping'    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'type' => 'getType',
'hydratemplate' => 'getHydratemplate',
'hydravariable_representation' => 'getHydravariableRepresentation',
'hydramapping' => 'getHydramapping'    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$swaggerModelName;
    }

    

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['type'] = isset($data['type']) ? $data['type'] : null;
        $this->container['hydratemplate'] = isset($data['hydratemplate']) ? $data['hydratemplate'] : null;
        $this->container['hydravariable_representation'] = isset($data['hydravariable_representation']) ? $data['hydravariable_representation'] : null;
        $this->container['hydramapping'] = isset($data['hydramapping']) ? $data['hydramapping'] : null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets type
     *
     * @return string
     */
    public function getType()
    {
        return $this->container['type'];
    }

    /**
     * Sets type
     *
     * @param string $type type
     *
     * @return $this
     */
    public function setType($type)
    {
        $this->container['type'] = $type;

        return $this;
    }

    /**
     * Gets hydratemplate
     *
     * @return string
     */
    public function getHydratemplate()
    {
        return $this->container['hydratemplate'];
    }

    /**
     * Sets hydratemplate
     *
     * @param string $hydratemplate hydratemplate
     *
     * @return $this
     */
    public function setHydratemplate($hydratemplate)
    {
        $this->container['hydratemplate'] = $hydratemplate;

        return $this;
    }

    /**
     * Gets hydravariable_representation
     *
     * @return string
     */
    public function getHydravariableRepresentation()
    {
        return $this->container['hydravariable_representation'];
    }

    /**
     * Sets hydravariable_representation
     *
     * @param string $hydravariable_representation hydravariable_representation
     *
     * @return $this
     */
    public function setHydravariableRepresentation($hydravariable_representation)
    {
        $this->container['hydravariable_representation'] = $hydravariable_representation;

        return $this;
    }

    /**
     * Gets hydramapping
     *
     * @return \VentureLeap\UserService\Model\InlineResponse200HydrasearchHydramapping[]
     */
    public function getHydramapping()
    {
        return $this->container['hydramapping'];
    }

    /**
     * Sets hydramapping
     *
     * @param \VentureLeap\UserService\Model\InlineResponse200HydrasearchHydramapping[] $hydramapping hydramapping
     *
     * @return $this
     */
    public function setHydramapping($hydramapping)
    {
        $this->container['hydramapping'] = $hydramapping;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed
     */
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     *
     * @param integer $offset Offset
     * @param mixed   $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(
                ObjectSerializer::sanitizeForSerialization($this),
                JSON_PRETTY_PRINT
            );
        }

        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}
