<?php
/**
 * AddressAddressWriteTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  VentureLeap\UserService
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * User API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.23
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace VentureLeap\UserService;

/**
 * AddressAddressWriteTest Class Doc Comment
 *
 * @category    Class
 * @description AddressAddressWrite
 * @package     VentureLeap\UserService
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class AddressAddressWriteTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "AddressAddressWrite"
     */
    public function testAddressAddressWrite()
    {
    }

    /**
     * Test attribute "street"
     */
    public function testPropertyStreet()
    {
    }

    /**
     * Test attribute "house_number"
     */
    public function testPropertyHouseNumber()
    {
    }

    /**
     * Test attribute "zip_code"
     */
    public function testPropertyZipCode()
    {
    }

    /**
     * Test attribute "city"
     */
    public function testPropertyCity()
    {
    }

    /**
     * Test attribute "country"
     */
    public function testPropertyCountry()
    {
    }

    /**
     * Test attribute "additional_information"
     */
    public function testPropertyAdditionalInformation()
    {
    }

    /**
     * Test attribute "address_type"
     */
    public function testPropertyAddressType()
    {
    }

    /**
     * Test attribute "user"
     */
    public function testPropertyUser()
    {
    }
}
