<?php
/**
 * InlineResponse200HydrasearchTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  VentureLeap\UserService
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * User API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.23
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace VentureLeap\UserService;

/**
 * InlineResponse200HydrasearchTest Class Doc Comment
 *
 * @category    Class
 * @description InlineResponse200Hydrasearch
 * @package     VentureLeap\UserService
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class InlineResponse200HydrasearchTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "InlineResponse200Hydrasearch"
     */
    public function testInlineResponse200Hydrasearch()
    {
    }

    /**
     * Test attribute "type"
     */
    public function testPropertyType()
    {
    }

    /**
     * Test attribute "hydratemplate"
     */
    public function testPropertyHydratemplate()
    {
    }

    /**
     * Test attribute "hydravariable_representation"
     */
    public function testPropertyHydravariableRepresentation()
    {
    }

    /**
     * Test attribute "hydramapping"
     */
    public function testPropertyHydramapping()
    {
    }
}
