<?php
/**
 * AddressApiTest
 * PHP version 5
 *
 * @category Class
 * @package  VentureLeap\UserService
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * User API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.20
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace VentureLeap\UserService;

use VentureLeap\UserService\Configuration;
use VentureLeap\UserService\ApiException;
use VentureLeap\UserService\ObjectSerializer;

/**
 * AddressApiTest Class Doc Comment
 *
 * @category Class
 * @package  VentureLeap\UserService
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class AddressApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for getAddressCollection
     *
     * Retrieves the collection of Address resources..
     *
     */
    public function testGetAddressCollection()
    {
    }

    /**
     * Test case for getAddressItem
     *
     * Retrieves a Address resource..
     *
     */
    public function testGetAddressItem()
    {
    }

    /**
     * Test case for postAddressCollection
     *
     * Creates a Address resource..
     *
     */
    public function testPostAddressCollection()
    {
    }

    /**
     * Test case for putAddressItem
     *
     * Replaces the Address resource..
     *
     */
    public function testPutAddressItem()
    {
    }
}
