<?php
/**
 * ApplicationApiTest
 * PHP version 5
 *
 * @category Class
 * @package  VentureLeap\ConfigurationService
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Configuration API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.20
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace VentureLeap\ConfigurationService;

use VentureLeap\ConfigurationService\Configuration;
use VentureLeap\ConfigurationService\ApiException;
use VentureLeap\ConfigurationService\ObjectSerializer;

/**
 * ApplicationApiTest Class Doc Comment
 *
 * @category Class
 * @package  VentureLeap\ConfigurationService
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class ApplicationApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for deleteApplicationItem
     *
     * Removes the Application resource..
     *
     */
    public function testDeleteApplicationItem()
    {
    }

    /**
     * Test case for getApplicationCollection
     *
     * Retrieves the collection of Application resources..
     *
     */
    public function testGetApplicationCollection()
    {
    }

    /**
     * Test case for getApplicationItem
     *
     * Retrieves a Application resource..
     *
     */
    public function testGetApplicationItem()
    {
    }

    /**
     * Test case for getTokenPost
     *
     * .
     *
     */
    public function testGetTokenPost()
    {
    }

    /**
     * Test case for postApplicationCollection
     *
     * Creates a Application resource..
     *
     */
    public function testPostApplicationCollection()
    {
    }

    /**
     * Test case for putApplicationItem
     *
     * Replaces the Application resource..
     *
     */
    public function testPutApplicationItem()
    {
    }
}
