<?php
/**
 * ConfigurationEntryApiTest
 * PHP version 5
 *
 * @category Class
 * @package  VentureLeap\UserService
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * LEAP.one - User Service
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.20
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace VentureLeap\UserService;

use VentureLeap\UserService\Configuration;
use VentureLeap\UserService\ApiException;
use VentureLeap\UserService\ObjectSerializer;

/**
 * ConfigurationEntryApiTest Class Doc Comment
 *
 * @category Class
 * @package  VentureLeap\UserService
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class ConfigurationEntryApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for deleteConfigurationEntryItem
     *
     * Removes the ConfigurationEntry resource..
     *
     */
    public function testDeleteConfigurationEntryItem()
    {
    }

    /**
     * Test case for getConfigurationEntryCollection
     *
     * Retrieves the collection of ConfigurationEntry resources..
     *
     */
    public function testGetConfigurationEntryCollection()
    {
    }

    /**
     * Test case for getConfigurationEntryItem
     *
     * Retrieves a ConfigurationEntry resource..
     *
     */
    public function testGetConfigurationEntryItem()
    {
    }

    /**
     * Test case for postConfigurationEntryCollection
     *
     * Creates a ConfigurationEntry resource..
     *
     */
    public function testPostConfigurationEntryCollection()
    {
    }

    /**
     * Test case for putConfigurationEntryItem
     *
     * Replaces the ConfigurationEntry resource..
     *
     */
    public function testPutConfigurationEntryItem()
    {
    }
}
