<?php
/**
 * UserApiTest
 * PHP version 5
 *
 * @category Class
 * @package  VentureLeap\UserService
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * User API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.23
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace VentureLeap\UserService;

use VentureLeap\UserService\Configuration;
use VentureLeap\UserService\ApiException;
use VentureLeap\UserService\ObjectSerializer;

/**
 * UserApiTest Class Doc Comment
 *
 * @category Class
 * @package  VentureLeap\UserService
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class UserApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for apiAccountsUsersGetSubresource
     *
     * Retrieves the collection of User resources..
     *
     */
    public function testApiAccountsUsersGetSubresource()
    {
    }

    /**
     * Test case for getToken
     *
     * Gets JWT token for a user.
     *
     */
    public function testGetToken()
    {
    }

    /**
     * Test case for getUserByTypeItem
     *
     * Retrieves a User resource..
     *
     */
    public function testGetUserByTypeItem()
    {
    }

    /**
     * Test case for getUserCollection
     *
     * Retrieves the collection of User resources..
     *
     */
    public function testGetUserCollection()
    {
    }

    /**
     * Test case for getUserItem
     *
     * Retrieves a User resource..
     *
     */
    public function testGetUserItem()
    {
    }

    /**
     * Test case for loginByTokenUserItem
     *
     * Get User resource from token.
     *
     */
    public function testLoginByTokenUserItem()
    {
    }

    /**
     * Test case for postCredentialsItem
     *
     * Check User Credentials.
     *
     */
    public function testPostCredentialsItem()
    {
    }

    /**
     * Test case for postPasswordRequest
     *
     * Checks User Email is correct and sends Password reset link.
     *
     */
    public function testPostPasswordRequest()
    {
    }

    /**
     * Test case for postUserCollection
     *
     * Creates a User resource..
     *
     */
    public function testPostUserCollection()
    {
    }

    /**
     * Test case for putUserItem
     *
     * Replaces the User resource..
     *
     */
    public function testPutUserItem()
    {
    }

    /**
     * Test case for resetUserPasswordUserItem
     *
     * Updates the User resource..
     *
     */
    public function testResetUserPasswordUserItem()
    {
    }

    /**
     * Test case for sendInvitationEmailUserItem
     *
     * Send Invitation email to User.
     *
     */
    public function testSendInvitationEmailUserItem()
    {
    }
}
